tests:
  non_fizz_non_buzz:
    assertStdoutEqual: 1
    data:
    - 1
    execute:
    - [ python3 fizzbuzz.py $(data) ]
    
  fizz:
    assertStdoutEqual: "Fizz"
    data:
    - 3
    execute:
    - [ python3 fizzbuzz.py $(data) ]
  
  buzz:
    assertStdoutEqual: "Buzz"
    data:
    - 5
    execute:
    - [ python3 fizzbuzz.py $(data) ]
  
  fizzbuzz:
    assertStdoutEqual: "FizzBuzz"
    data:
    - 15
    execute:
    - [ python3 fizzbuzz.py $(data) ]
  
  exception:
    assertStderr: True
    data:
    - A
    execute:
    - [ python3 fizzbuzz.py $(data) ]
